inline uptrszint getptr_wnrelease() {return (uptrszint) & wnrelease;}
inline uptrszint getptr_lexfiles() {return (uptrszint) & lexfiles;}
inline uptrszint getptr_ptrtyp() {return (uptrszint) & ptrtyp;}
inline uptrszint getptr_partnames() {return (uptrszint) & partnames;}
inline uptrszint getptr_partchars() {return (uptrszint) & partchars;}
inline uptrszint getptr_adjclass() {return (uptrszint) & adjclass;}
inline uptrszint getptr_frametext() {return (uptrszint) & frametext;}
inline uptrszint getptr_wnresults() {return (uptrszint) & wnresults;}
inline uptrszint getptr_fnflag() {return (uptrszint) & fnflag;}
inline uptrszint getptr_dflag() {return (uptrszint) & dflag;}
inline uptrszint getptr_saflag() {return (uptrszint) & saflag;}
inline uptrszint getptr_fileinfoflag() {return (uptrszint) & fileinfoflag;}
inline uptrszint getptr_frflag() {return (uptrszint) & frflag;}
inline uptrszint getptr_abortsearch() {return (uptrszint) & abortsearch;}
inline uptrszint getptr_offsetflag() {return (uptrszint) & offsetflag;}
inline uptrszint getptr_wnsnsflag() {return (uptrszint) & wnsnsflag;}
inline uptrszint getptr_OpenDB() {return (uptrszint) & OpenDB;}
inline uptrszint getptr_datafps() {return (uptrszint) & datafps;}
inline uptrszint getptr_indexfps() {return (uptrszint) & indexfps;}
inline uptrszint getptr_sensefp() {return (uptrszint) & sensefp;}
inline uptrszint getptr_cntlistfp() {return (uptrszint) & cntlistfp;}
inline uptrszint getptr_keyindexfp() {return (uptrszint) & keyindexfp;}
inline uptrszint getptr_revkeyindexfp() {return (uptrszint) & revkeyindexfp;}
inline uptrszint getptr_vidxfilefp() {return (uptrszint) & vidxfilefp;}
inline uptrszint getptr_vsentfilefp() {return (uptrszint) & vsentfilefp;}
inline uptrszint getptr_helptext() {return (uptrszint) & helptext;}
inline uptrszint getptr_license() {return (uptrszint) license;}
inline uptrszint getptr_dblicense() {return (uptrszint) dblicense;}
inline uptrszint getptr_interface_doevents_func() {return (uptrszint) & interface_doevents_func;}
inline uptrszint getptr_default_display_message() {return (uptrszint) & default_display_message;}
inline uptrszint getptr_display_message() {return (uptrszint) & getptr_display_message;}